export {default as Text} from './Text'
export {default as Anchor} from './Anchor'
export {default as Caption} from './Caption'
export {default as Block} from './Block'
export {default as GlobalStyle} from './GlobalStyle'